version: '3'
services:
  authz:
    build: .
    image: oli/authorization
    container_name: authz
    env_file: .envs
    environment:
      - MYSQL_PORT_3306_TCP_ADDR=mysql-authz
    ports:
     - "8081:8080"
     - "9991:9990"
    networks:
     - service-tier
    depends_on:
     - mysql-authz
  mysql-authz:
    image: mysql
    env_file: .envs
    networks:
      - service-tier
networks:
  service-tier:
    driver: bridge
